name: PrettySimpleShop
version: ${project.version}
#website:
author: RoboMWM
main: com.robomwm.prettysimpleshop.PrettySimpleShop
softdepend:
- Multiverse-Core
- Essentials
loadbefore:
- WorldGuard
- GriefPrevention
commands:
  setprice:
    usage: /setprice <price> - Sets the price per item of a shop.
  buy:
    usage: /buy <quantity> - Attempts to buy <quantity> amount from the selected shop (select a shop via left-clicking its chest).
  shop:
    usage: See /setprice, /buy
    aliases: [simpleshop, prettysimpleshop, pshop, psshop, sshop]