name: PrettySimpleShop
version: '${project.version}-${git.commit.id.abbrev}'
website: http://robomwm.com
authors: [Vrganj, RoboMWM]
main: com.robomwm.prettysimpleshop.PrettySimpleShop
api-version: '1.19'
softdepend:
- Multiverse-Core
- Essentials
loadbefore:
- WorldGuard
- GriefPrevention
commands:
  setprice:
    usage: /setprice <price> - Sets the price per item of a shop. Set to 0 to give away items for free, or set to -1 to disable the shop.
  psbuy:
    usage: /psbuy <quantity> - Attempts to buy <quantity> amount from the selected shop (select a shop via left-clicking its chest).
    aliases: [shopbuy, buyshop, simpleshopbuy, prettysimpleshopbuy, sbuy, pbuy, pssbuy]
  psshop:
    usage: Create a shop with /setprice. See /psbuy to buy from a shop.
    aliases: [simpleshop, prettysimpleshop, pshop, sshop]